### PR TITLE
added status

### PR DESCRIPTION
**Pull request by toooni**
added status for pending cancellation of an authorisation

### CODE REVIEW

**Comment by wysow** [comment]
Thanks @toooni but where this constant is used? Is it used automatically and it's just here for reference?

**Comment by toooni** [comment]
@wysow in our use case we're doing a maintenance request with operation DES (DirectLinkMaintenanceRequest::OPERATION_AUTHORISATION_DELETE_AND_CLOSE). In the answer we had cases where we do get a 61 (pending cancellation). It's an official STATUS.

**Comment by wysow** [comment]
OK @toooni got it, LGTM!

**Comment by wysow** [comment]
@toooni I'm wondering if you wish to have a release based on this PR?

**Comment by toooni** [comment]
@wysow sure.. if you don't mind. It's not very important to me because I do currently use the integer with a TODO comment to update to the constant one day ;)

**Comment by wysow** [comment]
@toooni Done https://github.com/wysow/wysow-postfinance/releases/tag/3.1.1

**Pull request merged**
