### PR TITLE
Ogone merge

### PR DESCRIPTION
**Pull request by toooni**
merged changes from ogone/master

### CODE REVIEW

**Comment by wysow** [comment]
Hello @toooni and thanks for this huge PR ;)

I'm going to review it entirely ASAP, but first thing you can do is delete the Ogone PDF files as I'm not sure they are really needed here, what do you think?

**Comment by toooni** [comment]
Hi @wysow you're welcome.. I was in the mood 💃

Already done.  

Take your time. Afaik there are no major changes but coding styles are bloating it a bit. I added them anyway because a future merge/rebase of the ogone repo will be a lot easier.
Test should be green btw.
I will now start to build a (PostfinanceDirectLink) Payum (https://github.com/Payum/Payum) gateway around the library.

**Comment by wysow** [comment]
@toooni I just tested phpunit locally and all seems OK ;)

Do you already used this code on a real project?

**Comment by wysow** [comment]
@toooni you deleted some images but not the PDF files, do you think they are necessary in a PostFinance context?

**Comment by wysow** [comment]
@toooni I just activated Travis on https://travis-ci.org/wysow/wysow-postfinance, so if you make another commit we wiil have a green result I hope ;)

**Comment by toooni** [comment]
@wysow No. Not yet. I just found your repo this morning ;) If you like you can wait until I finished the payum library. As soon as I do have it tested on staging, I'll write you. (At the moment I will just implement DirectLink)

I removed the PDF's. I think the problem is the new review tool from github. Just look at the last commit.

**Comment by wysow** [comment]
@toooni OK all green so LGTM this, and when you are sure everything is ok on your staging env. I will make a new release.

**Comment by toooni** [comment]
@wysow I tested DirectLinkPaymentRequest/Response and DirectLinkMaintenanceRequest/Response in staging. Everything seems to work great!

I won't implement more at the moment. But I am planning to use the ecommerce stuff soon too.

**Comment by wysow** [comment]
@toooni OK I'm going to do a new release then...

**Comment by wysow** [comment]
@toooni just done: https://github.com/wysow/wysow-postfinance/releases/tag/3.1.0

**Pull request merged**
