### PR TITLE
Update list of allowed sha-out parameters

### PR DESCRIPTION
**Pull request by wysow**
@SiddhyN here is a PR to update the list of parameters you mentioned in #6.

@tooni maybe you can test this before I merge as I currently do not have a project using this library.

### CODE REVIEW

**Comment by Tooni** [comment]
i think u messaged the wrong person m8

**Comment by wysow** [comment]
Sure @Tooni it was for @toooni instead... sorry for that ;)

**Comment by toooni** [comment]
@wysow I will check. Give me a day or two..

**Comment by wysow** [comment]
@toooni some news about this?

**Comment by toooni** [comment]
@wysow sorry.. I couldn't test in on dev easily because of not being able getting the response from the psp. I will test it as soon as I can test it on our staging environment.

**Comment by toooni** [comment]
@wysow sorry for taking so much time.. seems to work!

**Pull request merged**
